"""delete columns

Revision ID: 16ccfe23789f
Revises: 83f3aae9aaac
Create Date: 2025-04-04 10:58:52.125368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16ccfe23789f'
down_revision: Union[str, None] = '83f3aae9aaac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('WorldWeatherRepository', 'sunset')
    op.drop_column('WorldWeatherRepository', 'moonrise')
    op.drop_column('WorldWeatherRepository', 'moonset')
    op.drop_column('WorldWeatherRepository', 'sunrise')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('WorldWeatherRepository', sa.Column('sunrise', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('WorldWeatherRepository', sa.Column('moonset', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('WorldWeatherRepository', sa.Column('moonrise', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('WorldWeatherRepository', sa.Column('sunset', postgresql.TIME(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
