"""add column

Revision ID: afd1a69079bf
Revises: 16ccfe23789f
Create Date: 2025-04-04 14:20:15.674520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afd1a69079bf'
down_revision: Union[str, None] = '16ccfe23789f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('HeavenlyBodies', sa.Column('goingoutside', sa.Boolean(), nullable=False, server_default = sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('HeavenlyBodies', 'goingoutside')
    # ### end Alembic commands ###
