"""create table

Revision ID: 0c37eaa5b5d8
Revises: 
Create Date: 2025-04-04 10:30:44.511120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c37eaa5b5d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('HeavenlyBodies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sunrise', sa.Time(), nullable=False),
    sa.Column('sunset', sa.Time(), nullable=False),
    sa.Column('moonrise', sa.Time(), nullable=True),
    sa.Column('moonset', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('HeavenlyBodies')
    # ### end Alembic commands ###
